### PR TITLE
Added ESlint tool

### PR DESCRIPTION
**Pull request by aminadinari19**

### CODE REVIEW

**Comment by Abanoubr** [comment]
Hi Amina, 
As I noticed there is a failed test, in line 96 "Error: Process completed with exit code 1." I would suggest working on it together again today. We should check the npm.

**Comment by aminadinari19** [comment]
@Abanoubr I checked the tests. The problem seems to be with creation of components. This is absurd as the application works fine on my machine. We have to take a look at CI again.

**Comment by Abanoubr** [comment]
Ok thank you for your answer Amina, let's organise a team meeting for all the four of us today to work on it

**Comment by Abanoubr** [comment]
I believe today 19:00 pm will suit everyone

**Comment by Abanoubr** [comment]
@aminadinari19 @odiisus @mastertimisensei

**Comment by aminadinari19** [comment]
@Abanoubr  Anytime in this week is fine for me. I have changed the methods to prevent test from failing.

**Comment by aminadinari19** [comment]
The CI build is successful. Please approve the changes so we can merge them :)

**Comment by Abanoubr** [comment]
Awesome, seems like all is being prossesed really well.

**Pull request merged**
