### PR TITLE
Fixed rules for ESLINT

### PR DESCRIPTION
**Pull request by aminadinari19**

### CODE REVIEW

**Comment by aminadinari19** [comment]
@Abanoubr @odiisus @mastertimisensei Please take a look at this and try running this configuration of lint by using the command "ng lint".

**Comment by odiisus** [comment]
Great Amina have you checked the unit test after the change?

**Comment by Abanoubr** [comment]
well done @aminadinari19, finally the tests are flawless. The updated .eslintrc.js seems fine to me, I have no comments about it.

**Comment by Abanoubr** [comment]
Guys, let's follow up with the demoing the lint today in our afternoon meeting
@odiisus @mastertimisensei  @aminadinari19 
Thank y'all

**Comment by aminadinari19** [comment]
@odiisus yes the unit tests have been working fine unlike last time. And regarding the lint, I have added a couple of rules but you can add more if you'd like or we can also have super strict lint checking like the way of google style guide. Let me know which way you'd prefer.

**Comment by aminadinari19** [comment]
@Abanoubr Thanks. Let's move the meeting to evening if possible where we look at ways to clean up the repository and branches which are not needed anymore.

**Pull request merged**
